from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon, QPixmap


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        MainWindow.setProperty("scaledContents", True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnFnConfig = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFnConfig.sizePolicy().hasHeightForWidth())
        self.btnFnConfig.setSizePolicy(sizePolicy)
        self.btnFnConfig.setIcon(QIcon(QPixmap("./img/img_fn_setting.png")))
        self.btnFnConfig.setIconSize(QSize(20, 20))
        self.btnFnConfig.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.btnFnConfig.setText("")
        self.btnFnConfig.setObjectName("btnFnConfig")
        self.verticalLayout_8.addWidget(self.btnFnConfig)
        self.btnFnFilter = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFnFilter.sizePolicy().hasHeightForWidth())
        self.btnFnFilter.setSizePolicy(sizePolicy)
        self.btnFnFilter.setIcon(QIcon(QPixmap("./img/img_fn_filter.png")))
        self.btnFnFilter.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.btnFnFilter.setIconSize(QSize(20, 20))
        self.btnFnFilter.setText("")
        self.btnFnFilter.setObjectName("btnFnFilter")
        self.verticalLayout_8.addWidget(self.btnFnFilter)
        self.btnFnDelay = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFnDelay.sizePolicy().hasHeightForWidth())
        self.btnFnDelay.setSizePolicy(sizePolicy)
        self.btnFnDelay.setIcon(QIcon(QPixmap("./img/img_fn_delay_off.png")))
        self.btnFnDelay.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.btnFnDelay.setIconSize(QSize(20, 20))
        self.btnFnDelay.setText("")
        self.btnFnDelay.setObjectName("btnFnDelay")
        self.verticalLayout_8.addWidget(self.btnFnDelay)
        self.btnFnFlash = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFnFlash.sizePolicy().hasHeightForWidth())
        self.btnFnFlash.setSizePolicy(sizePolicy)
        self.btnFnFlash.setIcon(QIcon(QPixmap("./img/img_fn_flash_off.png")))
        self.btnFnFlash.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.btnFnFlash.setIconSize(QSize(20, 20))
        self.btnFnFlash.setText("")
        self.btnFnFlash.setObjectName("btnFnFlash")
        self.verticalLayout_8.addWidget(self.btnFnFlash)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnVideoAction = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnVideoAction.sizePolicy().hasHeightForWidth())
        self.btnVideoAction.setSizePolicy(sizePolicy)
        self.btnVideoAction.setIcon(QIcon(QPixmap("./img/img_video_action.png")))
        self.btnVideoAction.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.btnVideoAction.setIconSize(QSize(40, 40))
        self.btnVideoAction.setText("")
        self.btnVideoAction.setObjectName("btnVideoAction")
        self.verticalLayout_4.addWidget(self.btnVideoAction)
        self.btnCameraAction = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCameraAction.sizePolicy().hasHeightForWidth())
        self.btnCameraAction.setSizePolicy(sizePolicy)
        self.btnCameraAction.setIcon(QIcon(QPixmap("./img/img_camera_action.png")))
        self.btnCameraAction.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.btnCameraAction.setIconSize(QSize(40, 40))
        self.btnCameraAction.setText("")
        self.btnCameraAction.setObjectName("btnCameraAction")
        self.verticalLayout_4.addWidget(self.btnCameraAction)
        self.lblCamInfo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCamInfo.sizePolicy().hasHeightForWidth())
        self.lblCamInfo.setSizePolicy(sizePolicy)
        self.lblCamInfo.setAutoFillBackground(False)
        self.lblCamInfo.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblCamInfo.setTextFormat(QtCore.Qt.PlainText)
        self.lblCamInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCamInfo.setObjectName("lblCamInfo")
        self.verticalLayout_4.addWidget(self.lblCamInfo)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scnLiveView = QtWidgets.QLabel(self.centralwidget)
        self.scnLiveView.setAlignment(QtCore.Qt.AlignTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scnLiveView.sizePolicy().hasHeightForWidth())
        self.scnLiveView.setSizePolicy(sizePolicy)
        self.scnLiveView.setText("")
        self.scnLiveView.setProperty("FramelessWindowHint", "")
        self.scnLiveView.setObjectName("scnLiveView")
        self.gridLayout_3.addWidget(self.scnLiveView, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)